# Generated by Django 5.1.2 on 2024-10-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curso",
            name="codigo_curso",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
